version: '3.9'

services:
  react-app:
    image: nginx:alpine
    container_name: react-app
    ports:
      - "3002:80"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d:ro
    restart: unless-stopped
