version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3002:80"  # Changed to match Nginx's EXPOSE 80
    restart: unless-stopped
    environment:
      - NODE_ENV=production
